server:
  port : 8083
spring:
  datasource:
    url: jdbc:h2:file:./veaProject.h2
    driverClassName: org.h2.Driver
  messages:
    basename: aaa
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
accessType: jdbc
cxf:
  path: /ws
management:
  endpoints:
    web:
      exposure:
        include: "*"